return {
	diagnostics = {},
	git = {},
	gitsigns = {
		Add = "▎",
		Change = "▎",
		Delete = "契",
		TopDelete = "契",
		ChangeDelete = "契",
		Untracked = "┆",
	},
	kind = {
		Text = "",
		Method = "",
		Function = "",
		Constructor = "",
		Field = "",
		Variable = "",
		Class = "ﴯ",
		Namespace = "",
		Interface = "",
		Module = "",
		Property = "ﰠ",
		Unit = "塞",
		Value = "",
		Enum = "",
		Keyword = "",
		Snippet = "",
		Color = "",
		File = "",
		Reference = "",
		Folder = "",
		EnumMember = "",
		Constant = "",
		Struct = "",
		Event = "",
		Operator = "",
		TypeParameter = "",
	},
	ui = {},
}
