return {
	kind = {
		Text = "",
		Method = "",
		Function = "",
		Constructor = "",
		Field = "",
		Variable = "",
		Class = "ﴯ",
		Namespace = "",
		Interface = "",
		Module = "",
		Property = "ﰠ",
		Unit = "塞",
		Value = "",
		Enum = "",
		Keyword = "",
		Snippet = "",
		Color = "",
		File = "",
		Reference = "",
		Folder = "",
		EnumMember = "",
		Constant = "",
		Struct = "",
		Event = "",
		Operator = "",
		TypeParameter = "",
	},
	diagnostics = {
		Error = "",
		Warning = "",
		Information = "",
		Question = "",
		Hint = "",
	},
	ui = {
		ChevronRight = "",
		SymlinkArrow = "➛",
		DefaultFile = "",
		SymlinkFile = "",
		ArrowClosed = "",
		ArrowOpen = "",
		Folder = "",
		FolderOpen = "",
		EmptyFolder = "",
		EmptyFolderOpen = "",
		SymlinkFolder = "",
		SymlinkFolderOpen = "",
		IndentChar = "⁞",
	},
	git = {
		Unstaged = "",
		Staged = "",
		Unmerged = "",
		Renamed = "➜",
		Untracked = "",
		Deleted = "",
		Ignored = "◌",
	},
	gitsigns = {
		Add = "▎",
		Change = "▎",
		Delete = "契",
		TopDelete = "契",
		ChangeDelete = "契",
		Untracked = "┆",
	},
}
