require("ffl.options")
require("ffl.keymaps")
require("ffl.plugins")
-- require("ffl.stabilize")
require("ffl.autocommands")
require("ffl.colorscheme")
require("ffl.transparent")
require("ffl.cmp-npm")
require("ffl.cmp")
-- require("ffl.navic")
require("ffl.lsp")
require("ffl.telescope")
require("ffl.numb")
-- require("ffl.numbers")
require("ffl.treesitter")
require("ffl.autopairs")
require("ffl.comment")
require("ffl.leap")
require("ffl.gitsigns")
require("ffl.nvim-tree")
require("ffl.bufferline")
require("ffl.lualine")
require("ffl.toggleterm")
require("ffl.project")
require("ffl.impatient")
require("ffl.indentline")
require("ffl.alpha")
require("ffl.colorizer")
require("ffl.notify")
require("ffl.nvim-web-devicons")
require("ffl.illuminate")
require("ffl.dap")
-- require("ffl.winbar")
-- require("ffl.trouble")
require("ffl.crates")
require("ffl.dressing")
require("ffl.fidget")
require("ffl.persisted")
require("ffl.surround")
require("ffl.chartoggle")
